allergyProject/allergyProject/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp import views as mainviews
from searchapp import views as searchviews
from board import views as boardviews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainviews.home, name='home'),
    path('about/', mainviews.about, name='about'),
    # path('search/', searchviews.searchResult, name='search'),
    path('search/', include('searchapp.urls')),
    path('board/', boardviews.board, name='board'),
]

allergyProject/searchapp/urls.py
from django.urls import path
from . import views as searchviews

app_name = 'searchapp'

urlpatterns = [
    path('', searchviews.searchResult, name='searchResult'),
]

allergyProject/board/models.py
from django.db import models

# Create your models here.

allergyProject/searchapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    price = models.FloatField()
    digital = models.BooleanField(default=False, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    
    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

allergyProject/board/views.py
from django.shortcuts import render

# Create your views here.
def board (request):
    return render(request, 'board.html')

allergyProject/mainapp/views.py
from django.shortcuts import render

# Create your views here.
def home (request):
    return render(request, 'index.html')

def about (request):
    return render(request, 'about.html')

allergyProject/searchapp/views.py
from django.shortcuts import render
from .models import Product
from django.db.models import Q

# filter 함수의 Q함수: OR조건으로 데이터를 조회하기 위해 사용하는 함수
# objects.filter() 는 특정 조건에 해당하면 객체 출력 .get('kw') 은 kw만 반환
# __icontains 연산자 : 대소문자를 구분하지 않고 단어가 포함되어 있는지 검사. 사용법 "필드명"__icontains = 조건값

def searchResult(request):
    if 'kw' in request.GET:
        query = request.GET.get('kw')
        products = Product.objects.all().filter(
            Q(name__icontains=query) |
            Q(description__icontains=query)
        )  

    return render(request, 'search.html', {'query':query, 'products':products} )      

allergyProject/board/templates/board.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <!-- basic -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- mobile metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <!-- site metas -->
  <title>shree</title>
  <meta name="keywords" content="">
  <meta name="description" content="">
  <meta name="author" content="">
  <!-- fevicon -->
  <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
  <!-- bootstrap css -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <!-- style css -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!-- Responsive-->
  <link rel="stylesheet" href="{% static 'css/responsive.css' %}">  
  <!-- Scrollbar Custom CSS -->
  <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
  <!-- Tweaks for older IEs-->
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<!-- body -->

<body class="main-layout">
  <!-- loader  -->
  <div class="loader_bg">
    <div class="loader"><img src="{% static 'images/loading.gif' %}" alt="#" /></div>
  </div>
  <!-- end loader -->
  <!-- header -->
  <header>
    <!-- header inner -->
    <div class="header-top">
      <div class="header">
        <div class="container-fluid">
          <div class="row">
            <div class="col-xl-2 col-lg-4 col-md-4 col-sm-3 col logo_section">
              <div class="full">
                <div class="center-desk">
                  <div class="logo">
                    <a href="{% url 'home' %}"><img src="{% static 'images/logo.png' %}" alt="#" /></a>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xl-10 col-lg-8 col-md-8 col-sm-9">
         
               <div class="menu-area">
                <div class="limit-box">
                  <nav class="main-menu ">
                    <ul class="menu-area-main">
                      <li class="active"> <a href="{% url 'home' %}">Home</a> </li>
                      <li> <a href="{% url 'board' %}">Board</a> </li>
                      <li> <a href="{% url 'about' %}">About</a> </li>
                      <li> <a href="{% static '#contact' %}">Login</a> </li>
                     </ul>
                   </nav>
                 </div>
               </div> 
              </div>
           </div>
         </div>
       </div>
     </div>
     <!-- end header inner -->


<div class="col-xl-3 col-lg-3 col-md-3 col-sm-3" style="padding-top:100px;">
  <div class="about-box">
    <h2>게시판</h2>
  </div>
</div>

<br>
<div class="table">

  <table class="table table-striped">
    
    <thead>
      <tr>
      <th>번호</th>
      <th>제목</th>
      <th>작성자</th>
      <th>날짜</th>
      <th>조회수</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td>1</td>
      <td>대두 알레르기 환자를 위한 김치찌개</td>
      <td>대두</td>
      <td>22.11.06</td>
      <td>51</td>
    </tr>
    <tr>
      <td>2</td>
      <td>우유, 밀가루 없는 빵 만들기</td>
      <td>빵순이</td>
      <td>22.10.12</td>
      <td>102</td>
    </tr>
    <tr>
      <td>3</td>
      <td>간장게장 보단 간장연어장</td>
      <td>갑각률 알러지</td>
      <td>22.08.09</td>
      <td>211</td>
    </tr>
    </tbody>

  </table> 

<a class="btn btn-outline-secondary">글쓰기</a>

<div class="pagebutton">
  <ul class="pagination">
    <li><a class="page-link" href="#">이전</a></li>
    <li><a class="page-link" href="#">1</a></li>
    <li><a class="page-link" href="#">2</a></li>
    <li><a class="page-link" href="#">3</a></li>
    <li><a class="page-link" href="#">4</a></li>
    <li><a class="page-link" href="#">5</a></li>
    <li><a class="page-link" href="#">다음</a></li>
  </ul>
</div>

</div>
    <!--  footer -->
    <footr>
      <div class="footer ">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
             <a href="#" class="logo_footer"> <img src="{% static 'images/logo2.png' %}" alt="#"/></a>
            </div>
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 ">
              <div class="row">
                <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6 ">
                  <div class="address">
                    <h3>Address </h3>
                    <ul class="loca">
                      <li>
                        <a href="#"></a>It is a long established fact 
                        <br>that a reader will be  </li>
                        <li>
                          <a href="#"></a>(+71 1234567890) </li>
                          <li>
                            <a href="#"></a>demo@gmail.com</li>
                          </ul>
                        </div>
                      </div>
                      <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="address">
                          <h3>Social Link</h3>
                          <ul class="Menu_footer">
                            <li class="active"> <a href="#">Twitter</a> </li>
                            <li><a href="#">Facebook</a> </li>
                            <li><a href="#">Instagram</a> </li>
                            <li><a href="#">Linkdin</a> </li>
                          </ul>
                        </div>
                      </div>
                     

                      <div class="col-lg-4 col-md-6 col-sm-6 ">
                        <div class="address">
                          <h3>Newsletter</h3>
                           <form class="news">
                           <input class="newslatter" placeholder="Enter your email" type="text" name=" Enter your email">
                            <button class="submit">Subscribe</button>
                            </form>
                        </div>
                      </div>
                    </div>
                  </div>

                </div>

              </div>
              <div class="copyright">
                <div class="container">
                  <p>Copyright © 2019 Design by <a href="{% static '}https://html.design/' %">Free Html Templates </a></p>
                </div>
              </div>
            </div>
          </footr>
          <!-- end footer -->
          <!-- Javascript files-->
          <script src="{% static 'js/jquery.min.js' %}"></script>
          <script src="{% static 'js/popper.min.js' %}"></script>
          <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
          <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
          <script src="{% static 'js/plugin.js' %}"></script>
          <!-- sidebar -->
          <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
          <script src="{% static 'js/custom.js' %}"></script>
          <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>


          <script>
// This example adds a marker to indicate the position of Bondi Beach in Sydney,
// Australia.
function initMap() {
  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 11,
    center: {
      lat: 40.645037,
      lng: -73.880224
    },
  });

  var image = 'images/maps-and-flags.png';
  var beachMarker = new google.maps.Marker({
    position: {
      lat: 40.645037,
      lng: -73.880224
    },
    map: map,
    icon: image
  });
}
</script>
<!-- google map js -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA8eaHt9Dh5H57Zh0xVTqxVdBFCvFMqFjQ&callback=initMap"></script>
<!-- end google map js -->



</body>

</html>

allergyProject/mainapp/templates/about.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <!-- basic -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- mobile metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <!-- site metas -->
  <title>shree</title>
  <meta name="keywords" content="">
  <meta name="description" content="">
  <meta name="author" content="">
  <!-- fevicon -->
  <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
  <!-- bootstrap css -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <!-- style css -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!-- Responsive-->
  <link rel="stylesheet" href="{% static 'css/responsive.css' %}">  
  <!-- Scrollbar Custom CSS -->
  <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
  <!-- Tweaks for older IEs-->
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<!-- body -->

<body class="main-layout">
  <!-- loader  -->
  <div class="loader_bg">
    <div class="loader"><img src="{% static 'images/loading.gif' %}" alt="#" /></div>
  </div>
  <!-- end loader -->
  <!-- header -->
  <header>
    <!-- header inner -->
    <div class="header-top">
      <div class="header">
        <div class="container-fluid">
          <div class="row">
            <div class="col-xl-2 col-lg-4 col-md-4 col-sm-3 col logo_section">
              <div class="full">
                <div class="center-desk">
                  <div class="logo">
                    <a href="{% url 'home' %}"><img src="{% static 'images/logo.png' %}" alt="#" /></a>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xl-10 col-lg-8 col-md-8 col-sm-9">
         
               <div class="menu-area">
                <div class="limit-box">
                  <nav class="main-menu ">
                    <ul class="menu-area-main">
                      <li class="active"> <a href="{% url 'home' %}">Home</a> </li>
                      <li> <a href="{% static '#vegetable' %}">Board</a> </li>
                      <li> <a href="{% url 'about' %}">About</a> </li>
                      <li> <a href="{% static '#contact' %}">Login</a> </li>
                     </ul>
                   </nav>
                 </div>
               </div> 
              </div>
           </div>
         </div>
       </div>
     </div>
     <!-- end header inner -->

  <br> 

<!-- about  -->
<div id="about" class="about">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
        <div class="about-box">
          <h2>About us</h2>
          <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages andIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many</p>
          <a href="Javascript:void(0)">Read more</a>
        </div>
      </div>
      <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 padding_rl">
        <div class="about-box_img">
          <figure><img src="{% static 'images/about.jpg' %}" alt="#" /></figure>
        </div>
      </div>
    </div>

  </div>
</div>
<!-- end abouts -->


    <!--  footer -->
    <footr>
      <div class="footer ">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
             <a href="#" class="logo_footer"> <img src="{% static 'images/logo2.png' %}" alt="#"/></a>
            </div>
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 ">
              <div class="row">
                <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6 ">
                  <div class="address">
                    <h3>Address </h3>
                    <ul class="loca">
                      <li>
                        <a href="#"></a>It is a long established fact 
                        <br>that a reader will be  </li>
                        <li>
                          <a href="#"></a>(+71 1234567890) </li>
                          <li>
                            <a href="#"></a>demo@gmail.com</li>
                          </ul>
                        </div>
                      </div>
                      <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="address">
                          <h3>Social Link</h3>
                          <ul class="Menu_footer">
                            <li class="active"> <a href="#">Twitter</a> </li>
                            <li><a href="#">Facebook</a> </li>
                            <li><a href="#">Instagram</a> </li>
                            <li><a href="#">Linkdin</a> </li>
                          </ul>
                        </div>
                      </div>
                     

                      <div class="col-lg-4 col-md-6 col-sm-6 ">
                        <div class="address">
                          <h3>Newsletter</h3>
                           <form class="news">
                           <input class="newslatter" placeholder="Enter your email" type="text" name=" Enter your email">
                            <button class="submit">Subscribe</button>
                            </form>
                        </div>
                      </div>
                    </div>
                  </div>

                </div>

              </div>
              <div class="copyright">
                <div class="container">
                  <p>Copyright © 2019 Design by <a href="{% static '}https://html.design/' %">Free Html Templates </a></p>
                </div>
              </div>
            </div>
          </footr>
          <!-- end footer -->
          <!-- Javascript files-->
          <script src="{% static 'js/jquery.min.js' %}"></script>
          <script src="{% static 'js/popper.min.js' %}"></script>
          <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
          <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
          <script src="{% static 'js/plugin.js' %}"></script>
          <!-- sidebar -->
          <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
          <script src="{% static 'js/custom.js' %}"></script>
          <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>


          <script>
// This example adds a marker to indicate the position of Bondi Beach in Sydney,
// Australia.
function initMap() {
  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 11,
    center: {
      lat: 40.645037,
      lng: -73.880224
    },
  });

  var image = 'images/maps-and-flags.png';
  var beachMarker = new google.maps.Marker({
    position: {
      lat: 40.645037,
      lng: -73.880224
    },
    map: map,
    icon: image
  });
}
</script>
<!-- google map js -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA8eaHt9Dh5H57Zh0xVTqxVdBFCvFMqFjQ&callback=initMap"></script>
<!-- end google map js -->



</body>

</html>

allergyProject/mainapp/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <!-- basic -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- mobile metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <!-- site metas -->
  <title>shree</title>
  <meta name="keywords" content="">
  <meta name="description" content="">
  <meta name="author" content="">
  <!-- fevicon -->
  <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
  <!-- bootstrap css -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <!-- style css -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!-- Responsive-->
  <link rel="stylesheet" href="{% static 'css/responsive.css' %}">  
  <!-- Scrollbar Custom CSS -->
  <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
  <!-- Tweaks for older IEs-->
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<!-- body -->

<body class="main-layout">
  <!-- loader  -->
  <div class="loader_bg">
    <div class="loader"><img src="{% static 'images/loading.gif' %}" alt="#" /></div>
  </div>
  <!-- end loader -->
  <!-- header -->
  <header>
    <!-- header inner -->
    <div class="header-top">
      <div class="header">
        <div class="container-fluid">
          <div class="row">
            <div class="col-xl-2 col-lg-4 col-md-4 col-sm-3 col logo_section">
              <div class="full">
                <div class="center-desk">
                  <div class="logo">
                    <a href="{% url 'home' %}"><img src="{% static 'images/logo.png' %}" alt="#" /></a>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xl-10 col-lg-8 col-md-8 col-sm-9">
         
               <div class="menu-area">
                <div class="limit-box">
                  <nav class="main-menu ">
                    <ul class="menu-area-main">
                      <li class="active"> <a href="{% url 'home' %}">Home</a> </li>
                      <li> <a href="{% url 'board' %}">Board</a> </li>
                      <li> <a href="{% url 'about' %}">About</a> </li>
                      <li> <a href="{% static '#contact' %}">Login</a> </li>
                     </ul>
                   </nav>
                 </div>
               </div> 
              </div>
           </div>
         </div>
       </div>
     </div>
     <!-- end header inner -->

     <!-- end header -->
     <section class="slider_section">
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="container-fluid padding_dd">
              <div class="carousel-caption">
                <div class="row">
                  <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                    <div class="text-bg">
                     <span>Welcome To Aller View</span>
                      <h1>Allergy-Care Shop</h1>
                      <form class="Vegetable" action="{% url 'searchapp:searchResult' %}" method="get">
                        <input class="Vegetable_fom" placeholder="원하는 상품을 검색해보세요!" type="text" name="kw">
                        <button class="Search_btn">search</button>
                        
                      </form>
                    </div>
                  </div>
                  <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                    <div class="images_box">
                      <figure><img src="{% static 'images/allergyfood.jpg' %}"></figure>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div id="about" class="about">
    <div class="container-fluid">
      <div class="row" style="border-bottom:dashed;">
        <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3">
          <div class="about-box">
            <h2>이번달 식품 BEST</h2>
              <div class="about-box_img">
                <figure><img src="{% static 'images/about.jpg' %}" alt="#" /></figure>
              </div>
          </div>
        </div>
        <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3">
          <div class="about-box">
              <div class="about-box_img" style="padding-top:15%;">
                <figure><img src="{% static 'images/about.jpg' %}" alt="#" /></figure>
              </div>
          </div>
        </div>
        <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3">
          <div class="about-box">
              <div class="about-box_img" style="padding-top:15%;">
                <figure><img src="{% static 'images/about.jpg' %}" alt="#" /></figure>
              </div>
          </div>
        </div>
        <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3">
          <div class="about-box">
              <div class="about-box_img" style="padding-top:15%;">
                <figure><img src="{% static 'images/about.jpg' %}" alt="#" /></figure>
              </div>
              <div style="text-align:right;margin-right:5%;">
                <a href="{% static 'Javascript:void(0)' %}">더보기</a>
              </div> 
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3" >
          <div class="about-box">
            <h2>이번달 레시피 BEST</h2>
              <div class="about-box_img">
                <figure><img src="{% static 'images/about.jpg' %}" alt="#" /></figure>
              </div>
          </div>
        </div>
        <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3">
          <div class="about-box">
              <div class="about-box_img" style="padding-top:15%;">
                <figure><img src="{% static 'images/about.jpg' %}" alt="#" /></figure>
              </div>
          </div>
        </div>
        <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3">
          <div class="about-box">
              <div class="about-box_img" style="padding-top:15%;">
                <figure><img src="{% static 'images/about.jpg' %}" alt="#" /></figure>
              </div>
          </div>
        </div>
        <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3">
          <div class="about-box">
              <div class="about-box_img" style="padding-top:15%;">
                <figure><img src="{% static 'images/about.jpg' %}" alt="#" /></figure>
              </div>
              <div style="text-align:right;margin-right:5%;">
              <a href="{% static 'Javascript:void(0)' %}">더보기</a>
              </div>
          </div>
        </div>
      </div> 
    </div>
  </div>

</section>
</div>
</header>







    <!--  footer -->
    <footr>
      <div class="footer ">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
             <a href="#" class="logo_footer"> <img src="{% static 'images/logo2.png' %}" alt="#"/></a>
            </div>
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 ">
              <div class="row">
                <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6 ">
                  <div class="address">
                    <h3>Address </h3>
                    <ul class="loca">
                      <li>
                        <a href="#"></a>It is a long established fact 
                        <br>that a reader will be  </li>
                        <li>
                          <a href="#"></a>(+71 1234567890) </li>
                          <li>
                            <a href="#"></a>demo@gmail.com</li>
                          </ul>
                        </div>
                      </div>
                      <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="address">
                          <h3>Social Link</h3>
                          <ul class="Menu_footer">
                            <li class="active"> <a href="#">Twitter</a> </li>
                            <li><a href="#">Facebook</a> </li>
                            <li><a href="#">Instagram</a> </li>
                            <li><a href="#">Linkdin</a> </li>
                          </ul>
                        </div>
                      </div>
                     

                      <div class="col-lg-4 col-md-6 col-sm-6 ">
                        <div class="address">
                          <h3>Newsletter</h3>
                           <form class="news">
                           <input class="newslatter" placeholder="Enter your email" type="text" name=" Enter your email">
                            <button class="submit">Subscribe</button>
                            </form>
                        </div>
                      </div>
                    </div>
                  </div>

                </div>

              </div>
              <div class="copyright">
                <div class="container">
                  <p>Copyright © 2019 Design by <a href="{% static '}https://html.design/' %">Free Html Templates </a></p>
                </div>
              </div>
            </div>
          </footr>
          <!-- end footer -->
          <!-- Javascript files-->
          <script src="{% static 'js/jquery.min.js' %}"></script>
          <script src="{% static 'js/popper.min.js' %}"></script>
          <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
          <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
          <script src="{% static 'js/plugin.js' %}"></script>
          <!-- sidebar -->
          <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
          <script src="{% static 'js/custom.js' %}"></script>
          <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>


          <script>
// This example adds a marker to indicate the position of Bondi Beach in Sydney,
// Australia.
function initMap() {
  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 11,
    center: {
      lat: 40.645037,
      lng: -73.880224
    },
  });

  var image = 'images/maps-and-flags.png';
  var beachMarker = new google.maps.Marker({
    position: {
      lat: 40.645037,
      lng: -73.880224
    },
    map: map,
    icon: image
  });
}
</script>
<!-- google map js -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA8eaHt9Dh5H57Zh0xVTqxVdBFCvFMqFjQ&callback=initMap"></script>
<!-- end google map js -->



</body>

</html>